#!/bin/bash -e

npm install -g mesg-cli
mesg-cli daemon:start

# wait engine to be ready
sleep 10

# run http-server service
mesg-cli service:deploy https://github.com/antho1404/service-http-server
mesg-cli service:start http-server

# create an attachable network
docker network create --driver overlay --attachable marketplace

# run nginx proxy for ssl in marketplace's network
docker run --detach \
  --network marketplace  \
  --name nginx-proxy \
  --publish 80:80 \
  --publish 443:443 \
  --volume /etc/nginx/certs \
  --volume /etc/nginx/vhost.d \
  --volume /usr/share/nginx/html \
  --volume /var/run/docker.sock:/tmp/docker.sock:ro \
  jwilder/nginx-proxy

# configure letsencrypt to auto create certs for nginx proxy
docker run --detach \
  --name nginx-proxy-letsencrypt \
  --volumes-from nginx-proxy \
  --volume /var/run/docker.sock:/var/run/docker.sock:ro \
  jrcs/letsencrypt-nginx-proxy-companion

docker build -t marketplace .
docker service create --name marketplace \
  --network engine \
  marketplace

echo "Get the docker service ID of http-server"
echo "Execute:"
# following needs to be added to htt-server service:
echo "docker service update --network-add marketplace ID"
echo "docker service update \\"
echo "   --env-add \"VIRTUAL_HOST=marketplace.app.mesg.com\" \\"
echo "   --env-add \"VIRTUAL_PORT=2300\" \\"
echo "   --env-add \"LETSENCRYPT_HOST=marketplace.app.mesg.com\" \\"
echo "   --env-add \"LETSENCRYPT_EMAIL=info@mesg.com\" \\"
echo "   ID"